"""add llm request_timeout

Revision ID: d9cbd43b62e5
Revises: 440261f5594f
Create Date: 2026-04-01 18:18:53.009382
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd9cbd43b62e5'
down_revision: Union[str, None] = '440261f5594f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE llm_models ADD COLUMN IF NOT EXISTS request_timeout INTEGER")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_models', 'request_timeout')
    # ### end Alembic commands ###
