"""add open_files column to chat_session

Revision ID: 25811072c8fd
Revises: 45681b72317e
Create Date: 2026-04-15 17:56:32.270781
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25811072c8fd'
down_revision: Union[str, None] = '45681b72317e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_agent_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('gateway_messages')
    op.drop_index(op.f('ix_published_pages_agent_id'), table_name='published_pages')
    op.drop_index(op.f('ix_published_pages_short_id'), table_name='published_pages')
    op.drop_table('published_pages')
    op.drop_table('tenant_settings')
    op.add_column('chat_sessions', sa.Column('open_files', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('tenants', 'a2a_async_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'a2a_async_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('chat_sessions', 'open_files')
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_settings_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'key', name=op.f('tenant_settings_pkey'))
    )
    op.create_table('published_pages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('short_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('published_pages_agent_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('published_pages_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('published_pages_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('published_pages_pkey'))
    )
    op.create_index(op.f('ix_published_pages_short_id'), 'published_pages', ['short_id'], unique=True)
    op.create_index(op.f('ix_published_pages_agent_id'), 'published_pages', ['agent_id'], unique=False)
    op.create_table('gateway_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('gateway_messages_agent_id_fkey')),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], name=op.f('gateway_messages_sender_agent_id_fkey')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('gateway_messages_sender_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gateway_messages_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ref_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('notifications_agent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_agent_id'), 'notifications', ['agent_id'], unique=False)
    # ### end Alembic commands ###
