"""Add IDE plugin fields to chat_sessions

Revision ID: 29f3f8de3ca0
Revises: add_user_api_key
Create Date: 2026-04-12 14:58:51.550291
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f3f8de3ca0'
down_revision: Union[str, None] = 'add_user_api_key'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(col.get("name") == column_name for col in inspector.get_columns(table_name))


def _has_table(table_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def _has_index(table_name: str, index_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(idx.get("name") == index_name for idx in inspector.get_indexes(table_name))


def _has_unique_constraint(table_name: str, constraint_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(uc.get("name") == constraint_name for uc in inspector.get_unique_constraints(table_name))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_table('notifications'):
        if _has_index('notifications', op.f('ix_notifications_agent_id')):
            op.drop_index(op.f('ix_notifications_agent_id'), table_name='notifications')
        if _has_index('notifications', op.f('ix_notifications_created_at')):
            op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
        if _has_index('notifications', op.f('ix_notifications_user_id')):
            op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
        op.drop_table('notifications')
    if _has_table('published_pages'):
        if _has_index('published_pages', op.f('ix_published_pages_agent_id')):
            op.drop_index(op.f('ix_published_pages_agent_id'), table_name='published_pages')
        if _has_index('published_pages', op.f('ix_published_pages_short_id')):
            op.drop_index(op.f('ix_published_pages_short_id'), table_name='published_pages')
        op.drop_table('published_pages')
    if _has_table('gateway_messages'):
        op.drop_table('gateway_messages')
    if _has_table('tenant_settings'):
        op.drop_table('tenant_settings')
    if not _has_column('chat_sessions', 'client_type'):
        op.add_column('chat_sessions', sa.Column('client_type', sa.String(length=20), server_default='web', nullable=False))
    if not _has_column('chat_sessions', 'project_path'):
        op.add_column('chat_sessions', sa.Column('project_path', sa.String(length=500), nullable=True))
    if not _has_column('chat_sessions', 'current_file'):
        op.add_column('chat_sessions', sa.Column('current_file', sa.String(length=500), nullable=True))
    if _has_unique_constraint('users', op.f('users_api_key_hash_key')):
        op.drop_constraint(op.f('users_api_key_hash_key'), 'users', type_='unique')
    if _has_index('users', op.f('ix_users_api_key_hash')):
        op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    if not _has_index('users', op.f('ix_users_api_key_hash')):
        op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=False)
    op.create_unique_constraint(op.f('users_api_key_hash_key'), 'users', ['api_key_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('chat_sessions', 'current_file')
    op.drop_column('chat_sessions', 'project_path')
    op.drop_column('chat_sessions', 'client_type')
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_settings_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'key', name=op.f('tenant_settings_pkey'))
    )
    op.create_table('gateway_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('gateway_messages_agent_id_fkey')),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], name=op.f('gateway_messages_sender_agent_id_fkey')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('gateway_messages_sender_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gateway_messages_pkey'))
    )
    op.create_table('published_pages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('short_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('published_pages_agent_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('published_pages_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('published_pages_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('published_pages_pkey'))
    )
    op.create_index(op.f('ix_published_pages_short_id'), 'published_pages', ['short_id'], unique=True)
    op.create_index(op.f('ix_published_pages_agent_id'), 'published_pages', ['agent_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ref_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('notifications_agent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_agent_id'), 'notifications', ['agent_id'], unique=False)
    # ### end Alembic commands ###
